name: Jupyter Minimal Mistakes Workflow

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Jupyter Minimal Mistakes
      uses: ptmerz/jupyter-minimal-mistakes@v1.0.0

    - name: Build and deploy
      uses: EdricChan03/action-build-deploy-ghpages@v2.5.0
      env:
        JEKYLL_ENV: 'production'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
